### ISSUE TITLE
@aduskett @robybona PR #16 fixes DOMAIN and should make the behavior equal to the legacy py2 handling. Please test. Can I assume that this issue is indeed about DOMAIN and we can close it when PR #16 is merged? Thanks.

### ISSUE THREAD

**Issue by sarbazvatanatan** [Laerdal/python-objdictgen#17]
@aduskett @robybona PR #16 fixes DOMAIN and should make the behavior equal to the legacy py2 handling. Please test. Can I assume that this issue is indeed about DOMAIN and we can close it when PR #16 is merged? Thanks.

_Originally posted by @sveinse in https://github.com/Laerdal/python-objdictgen/issues/9#issuecomment-2053787014_

**Comment by sveinse** [comment]
Please post a proper question. I'm going to close this one.
