### ISSUE TITLE
Add reference to schema file

### ISSUE THREAD

**Issue by landrak** [Laerdal/python-objdictgen#37]
Add property `"$schema"` with a reference to the file https://github.com/Laerdal/python-objdictgen/blob/main/src/objdictgen/schema/od.schema.json to the *.json file format. This will help JSON tools and editors to validate and edit file files.

**Comment by sveinse** [comment]
https://www.schemastore.org/json/ could be a way to to it publicly. To do we need to commit the objdictgen schema as a PR to https://github.com/SchemaStore/schemastore

**Comment by sveinse** [comment]
According to[^1] the `$schema` field refers to the schema of the schema-file while `$id` contain the reference to the format which is describes[^2]. This is the current implementation and the `$id` reference is valid.

 [^1]: https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-00#rfc.section.8.1.1
 [^2]: https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-00#rfc.section.8.2.1
